version: '3.1'
services:
  nginx:
    image: rudiwork/nginx:dev
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./symfony/public:/app/public
    networks:
      - main
    # links:
    #  - php
  php:
    image: rudiwork/php7:dev
    volumes:
      - ./symfony:/app
    networks:
      - main
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      PHP_XDEBUG_REMOTE_HOST: 192.168.1.98
    # links:
    #  - pg

    user: 1000:1000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: gdfgdsds3453dafg
    volumes:
    # - mysqldata:/var/lib/mysql
      - ./mysql:/var/lib/mysql
      - ./db_dumps:/dumps
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - main

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - main

networks:
  main:
volumes:
  mysqldata:
